paths:
    - manifest: "resources/AndroidManifest.xml"
    - strings: "resources/res/values/strings.xml"

# These are the URLs that are used to check google API keys.
URLs:
    - maps: https://maps.googleapis.com/maps/api/staticmap?center=45%2C10&zoom=7&size=400x400&key=
    - streetview: https://maps.googleapis.com/maps/api/streetview?size=400x400&location=40.720032,-73.988354&fov=90&heading=235&pitch=10&key=
    - directions: https://maps.googleapis.com/maps/api/directions/json?origin=Disneyland&destination=Universal+Studios+Hollywood4&key=
    - places: https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=Museum%20of%20Contemporary%20Art%20Australia&inputtype=textquery&fields=photos,formatted_address,name,rating,opening_hours,geometry&key=
    - geocoding: https://maps.googleapis.com/maps/api/geocode/json?latlng=40,30&key=
